<?php
echo '<h1>NPG Monitor</h1>';
echo $this->form;
?>
<div role="tabpanel">

	<!-- Nav tabs -->
	<ul class="nav nav-tabs" role="tablist">
		<li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Requests</a></li>
		<li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Transaction</a></li>
		<li role="presentation"><a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">Logs</a></li>
	</ul>

	<!-- Tab panes -->
	<div class="tab-content">
		<div role="tabpanel" class="tab-pane active" id="home">
			<?php $this->printTable($this->requestsTable, $this->requestsTableFields, 'Requests', true); ?>
		</div>
		<div role="tabpanel" class="tab-pane" id="profile">
			<?php $this->printTable($this->transactionsTable); ?>
		</div>
		<div role="tabpanel" class="tab-pane" id="messages">
			<?php $this->printTable($this->logsTable); ?>
		</div>
	</div>

</div>


<?php
if (!empty($this->reqlog)):
	echo '<div class="technical-log"><h2>Request Technical Log</h2>';
	echo "<pre>" . htmlentities($this->reqlog) . "</pre></div>";
endif;
